language: node_js
node_js:
  - 10.15.0
  - stable
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
  - npm run build

after_script:
  cat ./coverage/lcov.info | ./node_modules/.bin/coveralls